services:
  - name: espazza-video-promotion-worker
    type: worker
    runtime: node
    buildCommand: npm install
    startCommand: node worker.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
