services:
  - type: worker
    name: espazza-video-promotion-worker
    env: node
    region: oregon
    buildCommand: npm ci --production
    startCommand: node worker.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
      - key: NODE_ENV
        value: production
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
