services:
  - type: worker
    name: espazza-video-promotion-worker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_PAGE_ID
        sync: false
